// <auto-generated />
using System;
using KUSYS_Demo.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KUSYS_Demo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221204123223_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KUSYS_Demo.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CourseRefId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CourseId");

                    b.ToTable("CourseData");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("0f575ca0-5501-43a3-b60d-3bcf92d590b6"),
                            CourseName = "Introduction to Computer Science",
                            CourseRefId = "CSI101",
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1890),
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1890)
                        },
                        new
                        {
                            CourseId = new Guid("c99f763b-9522-4099-a3da-b4d878b85055"),
                            CourseName = "Algorithms",
                            CourseRefId = "CSI102",
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1910),
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1920)
                        },
                        new
                        {
                            CourseId = new Guid("28a0a058-5da4-4db9-9423-bae56c52da99"),
                            CourseName = "Calculus",
                            CourseRefId = "MAT101",
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1920),
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1920)
                        },
                        new
                        {
                            CourseId = new Guid("2640bbb8-641a-4773-b827-4a525316867d"),
                            CourseName = "Physics",
                            CourseRefId = "PHY101",
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1930),
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1930)
                        });
                });

            modelBuilder.Entity("KUSYS_Demo.Entities.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("CourseUserId");

                    b.ToTable("CourseStudentData");
                });

            modelBuilder.Entity("KUSYS_Demo.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("UserData");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e252c16d-e71f-416c-8232-06bf4c466a26"),
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1640),
                            Email = "student@ku.edu.tr",
                            FirstName = "John",
                            LastName = "Doe",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1680),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("a116eced-dd57-49ed-898e-3ffb1841405f"),
                            UserRole = "Student"
                        },
                        new
                        {
                            UserId = new Guid("d7b08ad4-7f42-4ea8-9a1e-515a902e11e2"),
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1750),
                            Email = "10101234@ku.edu.tr",
                            FirstName = "Alex",
                            LastName = "Terry",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1750),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("578af524-ff19-41e9-85a3-91439c2c502d"),
                            UserRole = "Student"
                        },
                        new
                        {
                            UserId = new Guid("75e79228-5a13-4ad3-a107-f08fbe6575e5"),
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1770),
                            Email = "test1test1@ku.edu.tr",
                            FirstName = "test1",
                            LastName = "test11",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1770),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("32898aef-d627-4c2a-8d57-a2dc0e722aa2"),
                            UserRole = "Student"
                        },
                        new
                        {
                            UserId = new Guid("01a66959-d107-4bc7-b300-608c49aaa97f"),
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1780),
                            Email = "test2test2@ku.edu.tr",
                            FirstName = "test2",
                            LastName = "test22",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1780),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("b7e8492c-ba59-49d4-b557-5d2311742fcd"),
                            UserRole = "Student"
                        },
                        new
                        {
                            UserId = new Guid("e8784de4-3214-413a-86f5-0c426ac571b4"),
                            BirthDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1790),
                            Email = "test3test3@ku.edu.tr",
                            FirstName = "test3",
                            LastName = "test33",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1790),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("3d72d930-573e-4d85-b43f-340cff1f4c26"),
                            UserRole = "Student"
                        },
                        new
                        {
                            UserId = new Guid("6cf6b67a-5f67-43fd-874e-1b2a0c70ed11"),
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1810),
                            Email = "admin@ku.edu.tr",
                            FirstName = "Allen",
                            LastName = "Denswill",
                            Locked = false,
                            ModifiedDateTime = new DateTime(2022, 12, 4, 15, 32, 23, 97, DateTimeKind.Local).AddTicks(1810),
                            Password = "148506E98B3E74992CFF915C8CBD5591",
                            StudentId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserRole = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
